name: Deploy Flask App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Stopping any existing Flask app"
          pkill -f app.py || true
          
          echo "Navigating to cloudcomputing directory"
          cd ~/cloudcomputing || { echo "Directory not found"; exit 1; }
          
          echo "Pulling latest code from GitHub"
          git pull origin main || { echo "Git pull failed"; exit 1; }

          echo "Installing dependencies"
          pip3 install -r requirements.txt || { echo "Failed to install dependencies"; exit 1; }

          echo "Starting Flask app"
          nohup python3 app.py > output.log 2>&1 &

          echo "Flask app started, displaying logs"
          tail -f output.log
